name: example-cron
on:
  schedule:
    - cron: '* * * * 1'
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress nightly tests 🌃
        uses: ./
        with:
          working-directory: examples/basic
